### PR TITLE
Fix error on delete method

### LINKED ISSUE #41: Got 500 error on delete method
When I try delete file, the $filePath variable equals
`"/var/www/app/storage/app/filepond/rLW7knr1FRSjGkDI/avatar.jpeg"`
But if you use:
`Storage::disk('local')->delete($filePath)` , it should be:
"filepond/rLW7knr1FRSjGkDI/avatar.jpeg"
Is this error?

### PR DESCRIPTION
**Pull request by ryanito**
This PR fixes the delete method of the controller to correctly delete the folder for the uploaded file (closes #41). As mentioned in #42 it uses Laravel's `Storage` feature instead of local disk.

```php
public function delete(Request $request)
    {
        $absolutePathToFile = $this->filepond->getPathFromServerId($request->getContent());
        $storagePathToFile = strstr($absolutePathToFile, config('filepond.temporary_files_path', 'storage/app'));
        $storagePathToFolder = dirname($storagePathToFile);
        if (Storage::disk(config('filepond.temporary_files_disk', 'local'))->deleteDirectory($storagePathToFolder)) {
            return Response::make('', 200, [
                'Content-Type' => 'text/plain',
            ]);
        }

        return Response::make('', 500, [
            'Content-Type' => 'text/plain',
        ]);
    }```

### CODE REVIEW

**Review by dmalta — APPROVED** [review]

**Comment by patimio66** [comment]
@Sopamo please merge this pr.

**Comment by Sopamo** [comment]
@ryanito thanks for your contribution! Could you please update your PR to work with the latest [V1 release](https://github.com/Sopamo/laravel-filepond/releases/tag/v1.0)?

**Comment by ryanito** [comment]
> @ryanito thanks for your contribution! Could you please update your PR to work with the latest [V1 release](https://github.com/Sopamo/laravel-filepond/releases/tag/v1.0)?

All done!

**Comment by Sopamo** [comment]
Thanks for your contribution!

**Pull request merged**
